name: zzz-name

on:
  pull_request:
    branches:
      - staging
      - master
      - main
    types: [opened, edited, synchronize]

jobs:
  ccc-zzz:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4

      - name: Fetch base branch
        run: git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1

      - name: Check for SQL files
        id: check_sql
        run: |
          CHANGED_FILES=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }} HEAD)
          SQL_FILES=$(echo "$CHANGED_FILES" | grep '\.sql$' || true)

          if [[ -n "$SQL_FILES" ]]; then
            echo "found_sql=true" >> $GITHUB_ENV
          else
            echo "found_sql=false" >> $GITHUB_ENV
          fi

      - name: Check PR description for approval task
        id: check_task
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          BODY=$(gh pr view "$PR_NUMBER" --json body -q .body)

          CUSTOM_BODY="SIMPLE CUSTOM BODY 123"

          if [[ -n "$BODY" ]]; then 
            exit 1;
          fi
          gh pr edit "$PR_NUMBER" --body "$CUSTOM_BODY"

          echo "allow_sql=true" >> $GITHUB_ENV
          if [[ "$BODY" == *"- [ ] All DB migrations"* ]]; then
            echo "allow_sql=false" >> $GITHUB_ENV
          fi

      - name: Block merge if SQL files are found and task not approved
        run: |
          echo "found_sql=$found_sql"
          echo "allow_sql=$allow_sql"
          echo "skip_check=$skip_check"
          
          if [[ "$found_sql" == "true" && "$allow_sql" == "false" ]]; then
            echo "'Allow SQL files' task is not checked in the PR."
            exit 1
          fi
